name: LunarBreakerAPI
version: 25b34e0
description: CheatBreaker and Lunar Client API plugin
author: CheatBreaker Development Team
main: com.cheatbreaker.api.CheatBreakerAPI
load: STARTUP
commands:
  lc:
    aliases: ["lunarclient"]
  cb:
    aliases: ["cheatbreaker"]
  cbc:
    aliases: ["clientbroadcast"]